#!/bin/bash

# script setup: Set up the development environment.

set -e # Exit immediately if a command exits with a non-zero status.

python3 -m venv .venv # Create a virtual environment.
source .venv/bin/activate # Activate the virtual environment.

apt install shellcheck # Install shellcheck.
pip install poetry # Install poetry.
poetry install --no-root # Install dependencies.